//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 11:27:12 AM BST 
//


package uk.gov.gsi.hmrc.rest.dms.xmlobjects.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.gov.govtalk.hmrc.bit.config._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.gov.govtalk.hmrc.bit.config._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DfsConfigs }
     * 
     */
    public DfsConfigs createDfsConfigs() {
        return new DfsConfigs();
    }

    /**
     * Create an instance of {@link DfsConfigs.DfsConfig }
     * 
     */
    public DfsConfigs.DfsConfig createDfsConfigsDfsConfig() {
        return new DfsConfigs.DfsConfig();
    }

    /**
     * Create an instance of {@link DfsConfigs.DfsConfig.ImportRules }
     * 
     */
    public DfsConfigs.DfsConfig.ImportRules createDfsConfigsDfsConfigImportRules() {
        return new DfsConfigs.DfsConfig.ImportRules();
    }

    /**
     * Create an instance of {@link DfsConfigs.DfsConfig.ImportRules.MetaDataMappings }
     * 
     */
    public DfsConfigs.DfsConfig.ImportRules.MetaDataMappings createDfsConfigsDfsConfigImportRulesMetaDataMappings() {
        return new DfsConfigs.DfsConfig.ImportRules.MetaDataMappings();
    }

    /**
     * Create an instance of {@link DfsConfigs.DfsConfig.ImportRules.MetaDataMappings.MetaData }
     * 
     */
    public DfsConfigs.DfsConfig.ImportRules.MetaDataMappings.MetaData createDfsConfigsDfsConfigImportRulesMetaDataMappingsMetaData() {
        return new DfsConfigs.DfsConfig.ImportRules.MetaDataMappings.MetaData();
    }

}
