//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 11:27:12 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://govtalk.gov.uk/hmrc/bit/config/1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.gov.gsi.hmrc.rest.dms.xmlobjects.config;
